name: file_sharing
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3

dependencies:
  args: ^2.3.0
  shelf: ^1.4.1
  intl: ^0.18.1
  shelf_hotreload: ^1.4.0
  shelf_router: ^1.1.0
  shelf_web_socket: ^1.0.4
  web_socket_channel: ^2.4.0
  mailer: ^6.0.1
  shelf_static: ^1.1.2
  image: ^4.0.17

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0
